[versions]
activityCompose = "1.9.3"
composeBom = "2024.12.01"
coreKtx = "1.15.0"
lifecycle = "2.8.7"
kotlin = "2.0.21"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose" }
